### PR TITLE
Update META to fix dune support

### PR DESCRIPTION
**Pull request by hhugo**
I've missed the part that allows proper dune support for the jsoo stubs.

### CODE REVIEW

**Comment by hhugo** [comment]
Do you mind if I add a patch in the opam-repository for ptime.1.0  ?

**Comment by dbuenzli** [comment]
Yes I mind. Can't we rather eventually define how js_of_ocaml is meant to be compiled in the eco-system ?

**Comment by hhugo** [comment]
I don't understand what you want.

**Comment by dbuenzli** [comment]
Why does `dune` need this instruction ? Why isn't [that](https://github.com/dbuenzli/ptime/issues/24#issuecomment-1024542560) sufficient ? 

Can't we have a uniform way of specifying how `js_of_ocaml` stubs are meant to be compiled instead of having to repeat the same information in two different fields of  `META` files ? 

Can we have that documented somewhere ? So that build systems know how they should go about compiling `js_of_ocaml` programs that use libraries of the eco-system that have `js` stubs ?

**Comment by hhugo** [comment]
The `+package/path/to/file.js` syntax relying on ocamlfind was added to as a convenience for user calling the jsoo manually (the feature is optional) . A build system is probably supposed to know about the all the deps and can pass the correct path directly.

`linkopts(javascript) = "file.js"` in a META file was an attempt at fitting js_of_ocaml into ocamlfind, when no build system had proper support for jsoo  (see https://github.com/ocsigen/eliom/issues/13)

I'm not sure linkopts is the right tool for passing extra files to jsoo. What we want is to pass a file (relative or absolute path so that it's reachable by jsoo).

The `jsoo_runtime` way was added when I first added jsoo support inside dune/jbuilder (see https://github.com/ocaml/dune/pull/60). The goal was to have an entry similar to archive and have the build system combine it with the directory of the package before passing it to jsoo.

I've just spend some time trying to understand how to retrieve the information with `ocamlfind query` and I managed to get the following:
```
 $ ocamlfind query -r -format "%+(jsoo_runtime)" PACKAGE
```

```
$ ocamlfind query -r -format "%+(jsoo_runtime)" base  
/home/hugo/.opam/4.12.1/lib/base/base_internalhash_types/runtime.js



/home/hugo/.opam/4.12.1/lib/base/runtime.js
```

> Can't we have a uniform way of specifying how js_of_ocaml stubs are meant to be compiled instead of having to repeat the same information in two different fields of META files ?

I see the initial way of using linkopts as a hack for end user to use. I didn't know about many ocamlfind features at the time. The ocamlfind invocation above is seem better that the one relying on linkopt . Dune kept compatibility with the old way for convenience but maybe we should deprecate it somehow.


> Can we have that documented somewhere ? So that build systems know how they should go about compiling js_of_ocaml programs that use libraries of the eco-system that have js stubs ?

If we (who is we ?) agree on standardizing the use of jsoo_runtime, then yes we should document it.

@gerdstolpmann do you have anything to say about all this ?

**Comment by hhugo** [comment]
@dbuenzli, how do we proceed from there ?

Ping @gerdstolpmann

**Comment by dbuenzli** [comment]
> If we (who is we ?)

We in my case was users of the `js_of_ocaml` compiler. We in your case is whoever you want that to be.

Look `js_of_ocaml` is a fantastic tool but like the upstream compiler ocaml w.r.t. libraries it is handicaped by a lack of systems thinking. People repeatedly ask on discuss, how one goes on to use `js_of_ocaml` to provide bindings to js libraries and/or integrate javascript stub code and these things basically go unanswered because no one know for sure – and as witnessed by this PR, even not yourself apparently who, as far as I know, is the only one who is actually working on `js_of_ocaml`. 

Basically a precise account on how one goes to install libraries that provide JavaScript bindings. We need a library standard for `js_of_ocaml`. 

What is the install structure ? How do I query for these things I need to add at link step ? What if I have more than one `js` file to add ? What happens with recursive dependencies ? Do we really need `META` files, can't we simply link in `.js` files lying in the library directory (modulo a stable order) ? What are these fancy comments in front of javascript that you made me integrate in this repo that I know nothing about and I'm not even sure they are documented somewhere.

Prompted by the changes you suggested to me I already tweaked my build rules for [`brzo`](https://erratique.ch/software/brzo) and two weeks later you are telling me these changes do in fact not work with `dune` – and thus I suppose `dune` generated `META` files won't work with my build rules.

I'm willing to change my build rules and the `META` files of my packages to anything once there is a reliable piece of documentation that tells me how all of this is supposed to work. 

(I'm also willing to give you infinite feedback on whatever you come up with but my time will be very limited in the upcoming months).

**Comment by gerdstolpmann** [comment]
@hhugo I understand your need to get things working, and `META` is designed as extensible format. So yes, your ideas are probably all good.

@dbuenzli I guess you are also right when you say that these changes are a bit ad-hocish and that there's no doc specying anything (is that correct?).

If that describes the dispute, I think the solution is obvious - maybe @hhugo could write something where the ideas are described, and @dbuenzli gives feedback? - Just a suggestion, and I only comment because I was invited to the discussion.

**Pull request closed without merging**
